version: '3'

networks:
  laravel_web_client:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_laravel_web_client
    ports:
      - "12070:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel_web_client

  mysql:
    image: mysql:5.7.22
    container_name: mysql_laravel_web_client
    restart: unless-stopped
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "12377:3306"
    environment:
      MYSQL_DATABASE: laravel_web_client
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel_web_client

  pma2:
      depends_on:
       - mysql
      image: phpmyadmin/phpmyadmin
      container_name: pma2_laravel_web_client
      restart: always
      ports:
       - '12061:80'
      environment:
        PMA_HOST: mysql
      networks:
      - laravel_web_client
  
  # usage docker-compose run --rm php --version
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_laravel_web_client
    volumes:
      - ./src:/var/www/html
    ports:
      - "12022:9000"
    networks:
      - laravel_web_client

  # usage docker-compose run --rm composer dump-autoload -o
  composer:
    image: composer:latest
    container_name: composer_laravel_web_client
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - laravel_web_client
    
  # usage docker-compose run --rm artisan make:controller TestController
  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: artisan_laravel_web_client
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ['/var/www/html/artisan']
    networks:
      - laravel_web_client

  ###############################################################
  ################# Media Server Configuration ##################

  ## docker ps -aq | xargs docker stop | xargs docker rm

